apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: solr-dep
  name: solr-dep
spec:
  ports:
  - port: 8983
    protocol: TCP
    targetPort: 8983
  selector:
    app: solr-dep
  type: NodePort
status:
  loadBalancer: {}
